# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6d008e2480f9beebdfae34af55b998fd75b7a0a0ddd2dcaff77846a021efa3f23a296d97cd29cfba57d002c18d3561b7566dd2f4edd3eddba94cae2605961a

test:
  secret_key_base: 22b5a088b8200511d5e755d7455e6176ab8e8ced5b6359e9bf28dbc6306e6d6184ec03bbad9980a84e29e6598e9679ad1a073230768531dad7cb93846159b2f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
